import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Get started',
      link: {type: 'doc', id: 'get-started/index'},
      items: [
        'get-started/access',
        'get-started/install-lite',
        'get-started/first-run',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      link: {type: 'doc', id: 'concepts/index'},
      items: [
        'concepts/control-and-data-plane',
        'concepts/execution-lifecycle',
        'concepts/signals-events-patches',
      ],
    },
    {
      type: 'category',
      label: 'Author workflows',
      link: {type: 'doc', id: 'author/index'},
      items: [
        'author/core-dsl',
        'author/composition',
        'author/runtime-patches',
      ],
    },
    {
      type: 'category',
      label: 'Operate Tickr',
      link: {type: 'doc', id: 'operate/index'},
      items: [
        'operate/formations',
        'operate/configuration',
        'operate/storage-and-durability',
        'operate/security',
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      link: {type: 'doc', id: 'integrate/index'},
      items: [
        'integrate/http-lifecycle',
        'integrate/tickr-ctx',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'reference/index'},
      items: [
        'reference/cli',
        'reference/core-dsl',
        'reference/configuration',
        'reference/states',
        'reference/release-support',
      ],
    },
    {
      type: 'category',
      label: 'HTTP API',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
    'troubleshooting',
  ],
};

export default sidebars;
