/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["hello_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/clock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["dashboard_clock_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["dashboard_upcoming_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_events_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["api_health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patches/{patch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_patch_status_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patches/{patch_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_patch_source_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["cancel_signal_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/wakeup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["wakeup_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_signal_status_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["tenant_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_workflows_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_workflow_instance_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["cancel_workflow_instance_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_instance_context_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_workflow_instance_events_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["patch_instance_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["replay_instance_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/replays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_instance_replays_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_task_instances_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/tasks/{task_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["cancel_task_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/instances/{id}/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_task_instance_events_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["register_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["workflow_calendar_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{id}/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["list_workflow_instances_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_workflow_detail_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/instances/{workflow_instance_id}/tasks/{task_instance_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["get_task_logs_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflows/{workflow_id}/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * API operation
         * @description Public API contract.
         */
        post: operations["trigger_handler"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API operation
         * @description Public API contract.
         */
        get: operations["health_handler"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppliedPatchView: {
            applied_at: string;
            minted_map: {
                [key: string]: string;
            };
            ops: components["schemas"]["PatchOpView"][];
            patch_key: string;
            /** Format: int32 */
            prior_version: number;
            provenance: string;
            reason?: string | null;
            /** Format: int32 */
            version: number;
        };
        /** @description Public API contract. */
        AvailableVersion: {
            inserted_at: string;
            status: string;
            /** Format: int64 */
            version: number;
        };
        /** @description Public API contract. */
        CalendarResponse: {
            days: components["schemas"]["DayCounts"][];
            live_data_available: boolean;
            tz: string;
            /** Format: int32 */
            year: number;
        };
        /** @description Public API contract. */
        CancelResponse: {
            applied?: boolean | null;
            deduplicated?: boolean | null;
            /** Format: int32 */
            instances_matched?: number | null;
            /** Format: uuid */
            signal_id: string;
        };
        /** @description Public API contract. */
        CancelTargetBody: {
            /** @enum {string} */
            kind: "instance";
            /** Format: uuid */
            node_id?: string | null;
            /** Format: uuid */
            workflow_instance_id: string;
        } | {
            filter: {
                [key: string]: string;
            };
            /** @enum {string} */
            kind: "by_tag";
        };
        CaptureDeclarationResponse: {
            from: components["schemas"]["CaptureSourceResponse"];
            name: string;
        };
        CaptureSourceResponse: {
            Trigger: {
                jsonpath: string;
            };
        };
        /** @description Public API contract. */
        ClockInstance: {
            id: string;
            scheduled_at?: string | null;
            state: string;
            workflow_id: string;
            workflow_name: string;
        };
        /** @description Public API contract. */
        ClockResponse: {
            instances: components["schemas"]["ClockInstance"][];
            live_data_available: boolean;
        };
        /** @description Public API contract. */
        CommandPathHealth: {
            detail: string;
            detection_window: string;
            implementation: components["schemas"]["HealthRoleImplementation"];
            protocol: components["schemas"]["HealthProtocolIdentity"];
            status: components["schemas"]["ComponentStatus"];
        };
        /** @description Public API contract. */
        ComponentHealth: {
            detail: string;
            detection_window: string;
            status: components["schemas"]["ComponentStatus"];
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        ComponentStatus: "healthy" | "degraded" | "unhealthy";
        /** @description Public API contract. */
        CtxEntry: {
            created_at: string;
            /** @description Public API contract. */
            kind: string;
            /** @description Public API contract. */
            name: string;
            /** @description Public API contract. */
            present: boolean;
            /** @description Public API contract. */
            producer: string;
            secret: boolean;
            /** @description Public API contract. */
            value?: unknown;
        };
        /** @description Public API contract. */
        CtxGateScopeView: {
            entries: components["schemas"]["CtxEntry"][];
            signal_id: string;
        };
        /** @description Public API contract. */
        DataPlaneSqlHealth: {
            detail: string;
            detection_window: string;
            implementation: components["schemas"]["DataPlaneSqlImplementation"];
            status: components["schemas"]["ComponentStatus"];
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        DataPlaneSqlImplementation: "postgres" | "sqlite";
        /** @description Public API contract. */
        DayCounts: {
            /** Format: int64 */
            completed: number;
            date: string;
            /** Format: int64 */
            failed: number;
            /** Format: int64 */
            in_progress: number;
            /** Format: int64 */
            scheduled: number;
            /** Format: int64 */
            total: number;
        };
        /** @description Public API contract. */
        Event: {
            event_type: string;
            id: string;
            payload: unknown;
            /** Format: int64 */
            seq: number;
            ts: string;
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        ExecutorCapacityInterpretation: "observation_only";
        /** @description Public API contract. */
        ExecutorHealth: {
            capacity_interpretation: components["schemas"]["ExecutorCapacityInterpretation"];
            configured_process_slots?: number | null;
            detail: string;
            detection_window: string;
            /** Format: int64 */
            freshest_observation_age_ms?: number | null;
            in_flight_count?: number | null;
            /** Format: int64 */
            observation_ttl_ms?: number | null;
            observed_executors?: number | null;
            /** Format: int64 */
            oldest_observation_age_ms?: number | null;
            status: components["schemas"]["ComponentStatus"];
        };
        /** @description Public API contract. */
        FormationHealth: {
            detail: string;
            detection_window: string;
            /** Format: int32 */
            executor_count: number;
            final_logs: components["schemas"]["HealthFinalLogStore"];
            profile: components["schemas"]["HealthFormationProfile"];
            roles: components["schemas"]["HealthResolvedRole"][];
            sql: components["schemas"]["DataPlaneSqlImplementation"];
            status: components["schemas"]["ComponentStatus"];
            substrates: components["schemas"]["HealthSubstrateSelection"];
            topology: components["schemas"]["HealthFormationTopology"];
            writer_topology: components["schemas"]["HealthWriterTopology"];
        };
        GateView: {
            captures: string[];
            /** Format: int64 */
            duration_secs?: number | null;
            kind: string;
            op?: string | null;
            predicate?: string | null;
            routing_var?: string | null;
            signal_id?: string | null;
            signal_name?: string | null;
            state: string;
            /** Format: int64 */
            timeout_secs?: number | null;
            transitions: components["schemas"]["StateTransitionViewDoc"][];
            value?: null | components["schemas"]["RoutingValueView"];
        };
        /** @description Public API contract. */
        GenericCancelBody: {
            note?: string | null;
            target?: null | components["schemas"]["CancelTargetBody"];
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        HealthCoordinationRole: "command_bus" | "task_dispatch" | "task_events" | "task_cancellation" | "compaction_staging" | "lifecycle_work" | "log_staging" | "scope_store" | "ingress_idempotency_store" | "liveness_watchdog" | "signal_applied_notifier" | "executor_fleet_status" | "event_ingress";
        /**
         * @description Public API contract.
         * @enum {string}
         */
        HealthFinalLogStore: "local_files";
        /**
         * @description Public API contract.
         * @enum {string}
         */
        HealthFormationProfile: "tickr_lite";
        /**
         * @description Public API contract.
         * @enum {string}
         */
        HealthFormationTopology: "single_node";
        /** @description Public API contract. */
        HealthProtocolIdentity: {
            name: string;
            /** Format: int32 */
            version: number;
        };
        /** @description Public API contract. */
        HealthResolvedRole: {
            implementation: components["schemas"]["HealthRoleImplementation"];
            protocol: components["schemas"]["HealthProtocolIdentity"];
            role: components["schemas"]["HealthCoordinationRole"];
        };
        /** @description Public API contract. */
        HealthResponse: {
            api: components["schemas"]["ComponentHealth"];
            /** @description Public API contract. */
            checked_at: string;
            command_path?: null | components["schemas"]["CommandPathHealth"];
            conductor: components["schemas"]["ComponentHealth"];
            control_plane: components["schemas"]["ComponentHealth"];
            data_plane_sql: components["schemas"]["DataPlaneSqlHealth"];
            executors: components["schemas"]["ExecutorHealth"];
            formation?: null | components["schemas"]["FormationHealth"];
            local_coordination?: null | components["schemas"]["ComponentHealth"];
            nats_kv: components["schemas"]["ComponentHealth"];
            readiness?: null | components["schemas"]["ReadinessHealth"];
            redis_capability?: unknown;
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        HealthRoleImplementation: "local_request_reply" | "local_sqlite" | "local_journal" | "local_notification" | "local_observation" | "disabled";
        /** @description Public API contract. */
        HealthSubstrateSelection: {
            nats: boolean;
            object_store: boolean;
            postgres: boolean;
            redis: boolean;
            sqlite: boolean;
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        HealthWriterTopology: "conductor_owned";
        /** @description Public API contract. */
        HelloResponse: {
            message: string;
        };
        /** @description Public API contract. */
        IdentityRef: {
            code: string;
            id: string;
        };
        IdentityRefDoc: {
            code: string;
            id: string;
        };
        InputSourceViewDoc: {
            gate_edge_id?: string | null;
            kind: string;
            signal_name?: string | null;
            task?: string | null;
        };
        /** @description Public API contract. */
        InstanceContext: {
            gates: components["schemas"]["CtxGateScopeView"][];
            run: components["schemas"]["CtxEntry"][];
            storage: string;
            trigger: components["schemas"]["CtxEntry"][];
        };
        InstanceSnapshot: {
            applied_patches?: components["schemas"]["AppliedPatchView"][] | null;
            completed_at?: string | null;
            /** Format: int64 */
            completed_tasks: number;
            graph: components["schemas"]["SnapshotGraph"];
            id: string;
            name: string;
            routing_variables: {
                [key: string]: components["schemas"]["RoutingValueView"];
            };
            scheduled_at?: string | null;
            started_at?: string | null;
            state: string;
            storage: string;
            tags: {
                [key: string]: string;
            };
            /** Format: int64 */
            task_count: number;
            task_instances: components["schemas"]["SnapshotTaskInstance"][];
            tasks: components["schemas"]["SnapshotTaskDef"][];
            transitions: components["schemas"]["StateTransitionViewDoc"][];
            triggered_at?: string | null;
            triggered_by?: null | components["schemas"]["TriggerProvenanceView"];
            /** Format: int32 */
            version?: number | null;
            version_snapshots?: {
                [key: string]: components["schemas"]["SnapshotGraph"];
            } | null;
            workflow_id: string;
            workflow_name: string;
            /** Format: int64 */
            workflow_version: number;
        };
        PatchAcceptedResponse: {
            patch_id: string;
            status: components["schemas"]["PatchAcceptedStatus"];
        };
        /** @enum {string} */
        PatchAcceptedStatus: "accepted";
        /** @description Public API contract. */
        PatchBody: {
            /** @description Public API contract. */
            nickel_source: string;
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        PatchLifecycleStatus: "Validating" | "Building" | "Submitted" | "Applied" | "Rejected" | "BuildFailed";
        PatchOpView: {
            edge_id?: string | null;
            node_id?: string | null;
            op: string;
            sources: string[];
            targets: string[];
        };
        PatchRejectedResponse: {
            patch_id: string;
            reason: string;
            status: components["schemas"]["PatchRejectedStatus"];
        };
        /** @enum {string} */
        PatchRejectedStatus: "rejected";
        PatchSource: {
            /** Format: int64 */
            applied_version?: number | null;
            patch_id: string;
            source: string;
            source_format: string;
            workflow_instance_id: string;
        };
        PatchStatusResponse: {
            /** Format: int64 */
            applied_version: number | null;
            outcome: string | null;
            /** Format: uuid */
            patch_id: string;
            reason: string | null;
            status: components["schemas"]["PatchLifecycleStatus"];
            updated_at: string;
            /** Format: uuid */
            workflow_instance_id: string;
        };
        /** @description Public API contract. */
        PathCancelBody: {
            note?: string | null;
        };
        /** @description Public API contract. */
        ReadinessHealth: {
            detail: string;
            detection_window: string;
            ready: boolean;
            status: components["schemas"]["ComponentStatus"];
        };
        /** @description Public API contract. */
        ReadinessResponse: {
            status: string;
        };
        /** @description Public API contract. */
        RegisterBody: {
            namespace?: string;
            nickel_source: string;
        };
        /** @description Public API contract. */
        RegisterQueuedResponse: {
            message: string;
            status: components["schemas"]["RegisterQueuedStatus"];
            /** Format: int32 */
            task_count: number;
            workflow_id: string;
            /** Format: int64 */
            workflow_version: number;
        };
        /** @enum {string} */
        RegisterQueuedStatus: "Building" | "BuildRequeued";
        /** @description Public API contract. */
        RegisterSettledResponse: {
            message: string;
            status: components["schemas"]["RegisterSettledStatus"];
            workflow_id: string;
            /** Format: int64 */
            workflow_version: number;
        };
        /** @enum {string} */
        RegisterSettledStatus: "NoOp" | "Refreshed";
        /** @description Public API contract. */
        ReplayRequest: {
            idempotency_key?: string | null;
            /** @description Public API contract. */
            inputs?: {
                [key: string]: unknown;
            };
            name?: string | null;
            resume_from?: string[];
        };
        ReplayResult: {
            deduplicated?: boolean | null;
            doomed: string[];
            replay_instance_id: string;
        };
        /** @description Public API contract. */
        ReplayRow: {
            created_at: string;
            name?: string | null;
            replay_instance_id: string;
            resume_from: components["schemas"]["IdentityRef"][];
            shadowed_keys: string[];
            source_instance_id: string;
            status: string;
        };
        RoutingValueView: {
            kind: string;
            value: unknown;
        };
        RoutingVarDeclViewDoc: {
            name: string;
            var_type?: string | null;
        };
        /** @description Public API contract. */
        SignalStatusResponse: {
            /**
             * Format: int32
             * @description Public API contract.
             */
            applied_count?: number | null;
            /** @description Public API contract. */
            captures_summary?: string[];
            /**
             * Format: int32
             * @description Public API contract.
             */
            matched_workflows?: number | null;
            /** @description Public API contract. */
            name?: string | null;
            /** Format: uuid */
            signal_id: string;
            status: string;
            /** Format: uuid */
            workflow_id?: string | null;
            /** Format: uuid */
            workflow_instance_id?: string | null;
        };
        SnapshotEdgeDoc: {
            code: string;
            gates: components["schemas"]["GateView"][];
            id: string;
            kind: string;
            sources: string[];
            targets: string[];
        };
        SnapshotGraph: {
            edges: components["schemas"]["SnapshotEdgeDoc"][];
            end: string;
            nodes: components["schemas"]["SnapshotNodeDoc"][];
            start: string;
        };
        SnapshotNodeDoc: {
            code: string;
            ghost?: boolean | null;
            ground: string;
            grounded_at?: string | null;
            id: string;
            kind: string;
            pre_grounded?: boolean | null;
        };
        SnapshotTaskDef: {
            emits: components["schemas"]["TaskEmitViewDoc"][];
            id: string;
            inputs: components["schemas"]["TaskInputViewDoc"][];
            /** Format: int32 */
            max_attempts: number;
            name: string;
            nix_expression_path: string;
            outputs: string[];
            routing_vars: components["schemas"]["RoutingVarDeclViewDoc"][];
            secrets: string[];
            task_type: string;
            /** Format: int64 */
            timeout_secs?: number | null;
        };
        SnapshotTaskInstance: {
            /** Format: int32 */
            attempt: number;
            cancel_reason?: string | null;
            completed_at?: string | null;
            executor_id?: string | null;
            id: string;
            kill_confirmation?: string | null;
            name: string;
            started_at?: string | null;
            state: string;
            task_id: string;
            task_type: string;
            transitions: components["schemas"]["StateTransitionViewDoc"][];
        };
        StateTransitionViewDoc: {
            at: string;
            from: string;
            to: string;
        };
        TaskEmitViewDoc: {
            from_routing_var?: string | null;
            kind: string;
            signal_name: string;
        };
        TaskInputViewDoc: {
            name: string;
            source?: null | components["schemas"]["InputSourceViewDoc"];
        };
        /** @description Public API contract. */
        TaskInstance: {
            /** Format: int32 */
            attempt?: number;
            executor_id?: string | null;
            id: string;
            name: string;
            state: string;
            task_id: string;
            /** @description Public API contract. */
            task_type: string;
            workflow_id: string;
            workflow_instance_id: string;
        };
        /** @description Public API contract. */
        TaskLogBatch: {
            /** Format: int64 */
            seq: number;
            text: string;
        };
        /** @description Public API contract. */
        TaskLogBatchResponse: {
            batches: components["schemas"]["TaskLogBatch"][];
            exit_reason?: string | null;
            /** Format: int64 */
            exit_status?: number | null;
            has_earlier: boolean;
            /** Format: int64 */
            last_seq?: number | null;
            marker_present: boolean;
        };
        /** @description Public API contract. */
        TaskLogs: {
            exit_reason?: string | null;
            /** Format: int64 */
            exit_status?: number | null;
            logs: string;
            marker_present: boolean;
        };
        TaskLogsDocument: components["schemas"]["TaskLogs"] | components["schemas"]["TaskLogBatchResponse"];
        /** @description Public API contract. */
        TenantInfo: {
            id: string;
            slug: string;
            /** Format: int64 */
            workflow_count: number;
        };
        /** @description Public API contract. */
        Trigger: {
            Cron: string;
        } | "FireNow" | {
            WaitsOnSignal: components["schemas"]["WaitsOnSignalResponse"];
        };
        /** @description Public API contract. */
        TriggerBody: {
            inputs?: unknown;
            /** @description Public API contract. */
            name?: string | null;
            /** Format: date-time */
            scheduled_at?: string | null;
        };
        TriggerProvenanceView: {
            kind: string;
            name?: string | null;
            resume_from?: components["schemas"]["IdentityRefDoc"][] | null;
            signal_id?: string | null;
            source_instance?: null | components["schemas"]["IdentityRefDoc"];
        };
        /** @description Public API contract. */
        TriggerResult: {
            deduplicated: boolean;
            /** Format: date-time */
            scheduled_at?: string | null;
            /** Format: uuid */
            signal_id: string;
        };
        /** @description Public API contract. */
        UpcomingInstance: {
            name?: string;
            next_run_at?: string | null;
            workflow_id: string;
            workflow_instance_id: string;
            workflow_name: string;
        };
        WaitsOnSignalResponse: {
            captures?: components["schemas"]["CaptureDeclarationResponse"][];
            predicate?: string | null;
            signal_name: string;
        };
        /** @description Public API contract. */
        WakeupBody: {
            name?: string | null;
            payload?: unknown;
        };
        /** @description Public API contract. */
        WakeupResponse: {
            deduplicated?: boolean | null;
            /** Format: int32 */
            gates_matched?: number | null;
            /** Format: int32 */
            matched_workflows?: number | null;
            /** Format: uuid */
            signal_id: string;
        };
        /** @description Public API contract. */
        Workflow: {
            build_status: components["schemas"]["WorkflowBuildStatus"];
            /** Format: int64 */
            build_version?: number | null;
            /**
             * Format: int64
             * @description Public API contract.
             */
            completed_runs: number;
            id: string;
            /** @description Public API contract. */
            latest_run_state?: string | null;
            name: string;
            /** @description Public API contract. */
            namespace: string;
            slug: string;
            trigger: components["schemas"]["Trigger"];
            /** Format: int64 */
            version?: number | null;
        };
        /**
         * @description Public API contract.
         * @enum {string}
         */
        WorkflowBuildStatus: "Building" | "Ready" | "BuildFailed";
        /** @description Public API contract. */
        WorkflowDetail: {
            available_versions: components["schemas"]["AvailableVersion"][];
            /** Format: int64 */
            completed_runs: number;
            /** @description Public API contract. */
            latest_run_at?: string | null;
            latest_run_state?: string | null;
            /** @description Public API contract. */
            namespace: string;
            nickel_source: string;
            slug: string;
            /** Format: int64 */
            version: number;
            workflow_definition: unknown;
            workflow_id: string;
        };
        /** @description Public API contract. */
        WorkflowInstance: {
            completed_tasks: number;
            id: string;
            /** @description Public API contract. */
            name?: string;
            scheduled_at?: string | null;
            state: string;
            task_count: number;
            workflow_id: string;
            /**
             * Format: int64
             * @description Public API contract.
             */
            workflow_version?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    hello_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponse"];
                };
            };
        };
    };
    dashboard_clock_handler: {
        parameters: {
            query?: {
                start_time?: number | null;
                end_time?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClockResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    dashboard_upcoming_handler: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpcomingInstance"][];
                };
            };
        };
    };
    list_events_handler: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_patch_status_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchStatusResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_patch_source_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchSource"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_signal_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GenericCancelBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    wakeup_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WakeupBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WakeupResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_signal_status_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalStatusResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tenant_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantInfo"];
                };
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workflows_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"][];
                };
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_workflow_instance_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSnapshot"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_workflow_instance_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PathCancelBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_instance_context_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceContext"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workflow_instance_events_handler: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    patch_instance_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchAcceptedResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchRejectedResponse"];
                };
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    replay_instance_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReplayRequest"];
            };
        };
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResult"];
                };
            };
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_instance_replays_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayRow"][];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_task_instances_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskInstance"][];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancel_task_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PathCancelBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelResponse"];
                };
            };
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_task_instance_events_handler: {
        parameters: {
            query?: {
                after?: number | null;
            };
            header?: never;
            path: {
                id: string;
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterSettledResponse"];
                };
            };
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterQueuedResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workflow_calendar_handler: {
        parameters: {
            query: {
                year: number;
                tz?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_workflow_instances_handler: {
        parameters: {
            query?: {
                date?: string | null;
                tz?: string | null;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowInstance"][];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_workflow_detail_handler: {
        parameters: {
            query?: {
                version?: string | null;
            };
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetail"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_task_logs_handler: {
        parameters: {
            query?: {
                after_seq?: number | null;
                tail_batches?: number | null;
                before_seq?: number | null;
                download?: boolean | null;
            };
            header?: never;
            path: {
                workflow_id: string;
                workflow_instance_id: string;
                task_instance_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskLogsDocument"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_handler: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TriggerBody"];
            };
        };
        responses: {
            /** @description Public API contract. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TriggerResult"];
                };
            };
            /** @description Public API contract. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            408: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Public API contract. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_handler: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public API contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
